[devPis]
pi_dev ansible_host=pfoePi.local
pi_dev smb_share=//Server/share smb_user= smb_password=

[prodPis]
hum_signage1
hum_signage1 smb_share=//Server/share smb_user= smb_password=
hum_signage2
hum_signage2 smb_share=//Server/share smb_user= smb_password=
