# /etc/signagePi.conf

# Media Buff
MediaPufferPath=/home/__USER__/mediabuffer

# StartUp Config
# InfoScreenWait=5

# Samba Config
SambaShare=
SambaUser=
SambaPassword=

# SlideShow Config
SlideTime=5